- hosts: all
  become: true
  pre_tasks:

  - name: install updates for ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  roles:
    - web_server


- hosts: db_server
  become: true
  roles:
    - db_server


- hosts: all
  become: true
  roles:
    - base

