---

- hosts: all
  become: true
  tasks:

  - name: install updates for ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_server
  become: true
  tasks:

  - name: install apache2 package and add php support for apache
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
